targets:
  $default:
    sources:
      - lib/**
    builders:
      freezed:
        enabled: true
        generate_for:
          include:
            - lib/model/**
            - lib/bloc/**
      mobx_codegen:
        enabled: false
        generate_for:
          include:
            - lib/viewModel/**
     
      